### ISSUE TITLE
set/get stream attributes as javascript erizo client

### ISSUE THREAD

**Issue by pingrami** [zevarito/Licode-ErizoClientIOS#17]
Hi,
how can I set/get attributes of streams as javascript ErizoClient?

Paolo

**Comment by zevarito** [comment]
Hi @pingrami,

It is a good question, I thought @ashar02 has added that feature months ago but I cannot find it right now.

It should not be hard to implement, so if you are up yo it, please let me know how I can help you.

**Comment by pingrami** [comment]
Hi @zevarito ,
I'm watching the code written by @ashar02 in ECSignalingChannel.m in publish method (is different from your branch), so I understand I have to add an inner dictionary on options dictionary with key "customOptions" used to set attributes stream like javascript Erizo Client. Show below my implementation of room:didConnenct in swift where local stream is published:

Thanks very much!

    public func room(room: ECRoom!, didConnect roomMetadata: [NSObject : AnyObject]!) {
        self.showCallConnectViews(false, statusMessage: "Room connected!")
        // We get connected and ready to publish, so publish.
        var options = [String:AnyObject]()
        options["maxVideoBW"] = "300"
        var attributes = [String:String]()
        attributes["name"] = "myStreamAV-iOS"
        attributes["typeStream"] = "av"
        options["customOptions"] = attributes
        remoteRoom.publish(localStream, withOptions: options)
        
    }    public func room(room: ECRoom!, didConnect roomMetadata: [NSObject : AnyObject]!) {
        self.showCallConnectViews(false, statusMessage: "Room connected!")
        // We get connected and ready to publish, so publish.
        var options = [String:AnyObject]()
        options["maxVideoBW"] = "300"
        var attributes = [String:String]()
        attributes["name"] = "myStreamAV-iOS"
        attributes["typeStream"] = "av"
        options["customOptions"] = attributes
        remoteRoom.publish(localStream, withOptions: options)
        
    }

**Comment by zevarito** [comment]
I'd suggest you to take a look at how JS Api is handling it and try to
reproduce it as much as you can.

2016-03-07 13:55 GMT-03:00 pingrami <notifications@github.com>:

> Hi @zevarito <https://github.com/zevarito> ,
> I'm watching the code written by @ashar02 <https://github.com/ashar02> in
> ECSignalingChannel.m in publish method (is different from your branch), so
> I understand I have to add an inner dictionary on options dictionary with
> key "customOptions" used to set attributes stream like javascript Erizo
> Client. Show below my implementation of room:didConnenct in swift where
> local stream is published:
>
> Thanks very much!
>
> public func room(room: ECRoom!, didConnect roomMetadata: [NSObject : AnyObject]!) {
>     self.showCallConnectViews(false, statusMessage: "Room connected!")
>     // We get connected and ready to publish, so publish.
>     var options = [String:AnyObject]()
>     options["maxVideoBW"] = "300"
>     var attributes = [String:String]()
>     attributes["name"] = "myStreamAV-iOS"
>     attributes["typeStream"] = "av"
>     options["customOptions"] = attributes
>     remoteRoom.publish(localStream, withOptions: options)
>
> }    public func room(room: ECRoom!, didConnect roomMetadata: [NSObject : AnyObject]!) {
>     self.showCallConnectViews(false, statusMessage: "Room connected!")
>     // We get connected and ready to publish, so publish.
>     var options = [String:AnyObject]()
>     options["maxVideoBW"] = "300"
>     var attributes = [String:String]()
>     attributes["name"] = "myStreamAV-iOS"
>     attributes["typeStream"] = "av"
>     options["customOptions"] = attributes
>     remoteRoom.publish(localStream, withOptions: options)
>
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zevarito/ErizoClientIOS/issues/17#issuecomment-193343318>
> .
>



-- 
Alvaro

**Comment by zevarito** [comment]
@pingrami you can set custom attributes at publishing time.

`- (void)publish:(ECStream *)stream withOptions:(NSDictionary *)options`

`options` should have a key named `attributes` with your own key/values.
