### ISSUE TITLE
Crash on Lock screen iOS

### ISSUE THREAD

**Issue by rabiea** [zevarito/Licode-ErizoClientIOS#25]
I am using non-patched Licode version and non-patched erizo client version. This crash is easily reproducible. while you are in conference just press lock screen button and just unlock the screen
[Logs.zip](https://github.com/zevarito/Licode-ErizoClientIOS/files/253316/Logs.zip)
 and after that the application gets disconnected. I am attaching the logs.

**Comment by ashar02** [comment]
@zevarito 
I want to make fix of it. Is there some thing you have in mind to address this issue. It may help me to get some ground from you before start.

**Comment by zevarito** [comment]
@ashar02 sorry, couldn't look into this yet, not even take a backtrace to study, if you have something in mind please go ahead.
