### ISSUE TITLE
Compile the project

### ISSUE THREAD

**Issue by ntanitime** [zevarito/Licode-ErizoClientIOS#31]
I am not able to start the project, I got these errors after all the procedure:

`error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-ErizoClient
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-ErizoClient is not an object file (not allowed in a library)`

I also got an warning:

`Target 'Pods-ErizoClient' of project 'Pods' was rejected as an implicit dependency for 'libPods-ErizoClient.a' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'`

Can someone help me?

**Comment by rabiea** [comment]
select ErizoClientIOS goto its Build Settings set Build For Active Architecture Only to YES
after that select ECIExampleLicode select goto its Build Settings set Build For Active Architecture Only to YES
