### ISSUE TITLE
unable to deallocate local stream

### ISSUE THREAD

**Issue by rabiea** [zevarito/Licode-ErizoClientIOS#32]
@zevarito I am unable to deallocate local stream. I have tried to remove the renderer but still local stream is present.
(videoadapter.cc:330): VAdapt Frame: scaled 0 / out 90 / in 90 Changes: 0 Input: 480x640 i33333333 Scale: 1 Output: 480x640 i33333333 Changed: false
(videoadapter.cc:330): VAdapt Frame: scaled 0 / out 180 / in 180 Changes: 0 Input: 480x640 i33333333 Scale: 1 Output: 480x640 i33333333 Changed: false
(videoadapter.cc:330): VAdapt Frame: scaled 0 / out 270 / in 270 Changes: 0 Input: 480x640 i33333333 Scale: 1 Output: 480x640 i33333333 Changed: false

**Comment by zevarito** [comment]
Hi @rabiea, did you make it work?

I am not working in this library since weeks, I will be jumping in again really soon, perhaps give me details about what you were doing so I can try to reproduce.

**Comment by rabiea** [comment]
@zevarito yes i managed to deallocate the local stream. you need to remove the video from stream when you leave the room, otherwise renderer doesn't get deallocated.
