### ISSUE TITLE
Unable Cloning project

### ISSUE THREAD

**Issue by zhangguoyong** [zevarito/Licode-ErizoClientIOS#33]
$ git clone git@github.com:zevarito/ErizoClientIOS.git
Cloning into 'ErizoClientIOS'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

Thanks

**Comment by zevarito** [comment]
@zhangguoyong The repo is public so you should not have any issue to clone it. Are you sure your pubkey is in your github account?
