### ISSUE TITLE
'RTCEAGLVideoView.h' file not found

### ISSUE THREAD

**Issue by kalvish** [zevarito/Licode-ErizoClientIOS#34]
Any Idea why this comes up in 'ECIExampleLicode' project?

**Comment by zevarito** [comment]
@kalvish did you installed `pod` and perform `pod install`?

**Comment by hameed444** [comment]
Here is a fix.

Steps i followed :

1.Clone github repo.
2.run pod install.
3. Open **ErizoClientIOS.workspace**
4.select **Erizoclient scheme** , build  successful.
5.Select **ECILicodeExampleLicode Pods**  , build successful. Run with this scheme.
