### ISSUE TITLE
Erizo-android

### ISSUE THREAD

**Issue by zhangguoyong** [zevarito/Licode-ErizoClientIOS#39]
Hi  friend. Do you know how to build  a   Android  app with java code not web  。There are too many demos on the internet.But with java code I only find one and not work well. Thank you very much

**Comment by zevarito** [comment]
@zhangguoyong no I don't, if you find an Erizo Android implementation that works, please let me know!

**Comment by hameed444** [comment]
you can use cross walk for android.link is here:
https://crosswalk-project.org/

**Comment by zhangguoyong** [comment]
@hameed444  hi friend , how to use the  cross walk. I want to develop video by   android native
 code ,thanks.
