### ISSUE TITLE
can't locate file for: -lPods-ErizoClient

### ISSUE THREAD

**Issue by lotusking** [zevarito/Licode-ErizoClientIOS#40]
When building ErizoClientIOS after "pod install", there are errors like this:

error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-ErizoClient
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-ErizoClient is not an object file (not allowed in a library)

**Comment by geoffery009** [comment]
Maybe you need focus this warnning and change the Valid Architectures:
Xcode：Target of project Pods was rejected as an implicit dependency for because its architectures x86_64 didn’t contain all required architectures i386 x86_64

**Comment by hameed444** [comment]
ok this error can easily be removed , follow these steps to remove.
1. select "ErizoCleint" scheme Clean and build project.(it should build
successfully)
2.Now select "ECIExampleLicode pods" and again clean and build.
3.if it gives error then goto Build Phases , then link Binary with
Libraries and remove -lPods-ErizoClient .a
4.now clean and build , it will run successfully.

if doesnt work reply here again

**Comment by ansonlo** [comment]
Please add the Targets to Main ECIExampleLicode Target. Then build.
![qq 20170209173220](https://cloud.githubusercontent.com/assets/878868/22777324/d1ae3f4e-eeed-11e6-9b18-b6200bd6fedb.png)
