### ISSUE TITLE
Got a black video view 

### ISSUE THREAD

**Issue by jk67954** [zevarito/Licode-ErizoClientIOS#41]
I have test the last ErizoClientIOS Demo and it can communicate with licode demo server ,but video render a black view ,i can't find some error about this problem. The log file and screenshot is below
<img width="478" alt="qq20161009-0 2x" src="https://cloud.githubusercontent.com/assets/1383781/19218883/f2b1f896-8e37-11e6-80ad-5238b694912b.png">
[logs-erizoclient_ios.txt](https://github.com/zevarito/Licode-ErizoClientIOS/files/518167/logs-erizoclient_ios.txt)

**Comment by zevarito** [comment]
@jk67954 Accordingly to your logs they show Turn/Stun negotiation errors, since you were testing with Licode servers this issue might be resolved, see: https://groups.google.com/forum/#!msg/lynckia/Cvvdx7vxu3c/T0e9grc1GAAJ

I'll close this, please re-open if your issue is different than that.
