### ISSUE TITLE
Errors building the project

### ISSUE THREAD

**Issue by sferrini** [zevarito/Licode-ErizoClientIOS#42]
Hi @zevarito 

I have some problem running this project:

What I did is clone the repo, and run `pod install`:

![screen shot 2016-10-20 at 19 35 51](https://cloud.githubusercontent.com/assets/3370782/19570972/7579db32-96fc-11e6-8d56-e28b73a66239.png)

This gives me the error : _`Unable to satisfy the following requirement`_

So I modified the `Podfile` as follows (removed the version to the `libjingle_peerconnection` pod):

```ruby
platform :ios, "8.0"

workspace "./ErizoClientIOS.xcworkspace"

target "ErizoClient" do
  platform :ios, "8.0"
  project "ErizoClientIOS"
  pod "libjingle_peerconnection"
end

target "ECIExampleLicode pods" do
  platform :ios, "8.0"
  project "ECIExampleLicode/ECIExampleLicode"
  pod "libjingle_peerconnection"
end
```

Then removed the `Podfile.lock` and `pod install` again:

![screen shot 2016-10-20 at 19 41 41](https://cloud.githubusercontent.com/assets/3370782/19571155/529b9dca-96fd-11e6-9220-8fd1ad5c7f40.png)

Now, I've tried to open the project anyway also if the `pod install` gives warnings:

![screen shot 2016-10-20 at 19 47 43](https://cloud.githubusercontent.com/assets/3370782/19571348/1769b06a-96fe-11e6-95e6-b5364c9e6612.png)

But as you see, there are errors at compile time too.

Any advice?

Thanks

**Comment by sferrini** [comment]
Yep, actually reading this (https://github.com/zevarito/Licode-ErizoClientIOS/issues/40)  issue, thanks to the @geoffery009 comment, I kind of solved the problem. I'm now able to compile for ARM devices but still not be able to compile for x86_64.

@zevarito should I close this issue or should we keep it here to remind that x86_64 arch is missing from the lib?

Thanks

**Comment by zevarito** [comment]
@sferrini let's close this and open another one. Thanks.
