### ISSUE TITLE
Erizo iOS Client not working in P2P Mode

### ISSUE THREAD

**Issue by NarendraDigi** [zevarito/Licode-ErizoClientIOS#45]
Hi , 
I am trying to Video conferencing in P2P mode.
i did following setting for P2P . 
{
data: true,
state: p2p
}
But it is not working . Is there any thing should i change in my code .
Plz help me to do that .

Thanks

Narendra Satpute

**Comment by zevarito** [comment]
@NarendraDigi Can you elaborate a little more about how it is not working?

* There is some visible error? What the app log say?
* Did you check Nuve/ErizoController logs? What show them?

**Comment by NarendraDigi** [comment]
Thanks for reply. Let me elaborate our use case – 

Our app operates in 2 modes based on the customer & server setting – MCU & P2P. 
Desired functionality: Based on the server setting( P2P & MCU) the IOS client should connect in the correct mode.
For testing purposes we have deployed 2 servers – 1 in MCU mode & 1 in P2P mode.
MCU work perfectly from IOS using the Erizo IOS client.


I am trying to get video conferencing in P2P mode working for the IOS app ( IOS > Web OR IOS > IOS)
Video conferencing is not working when  my server is in P2P mode.

The connection is getting established but the servcer sends an event called “Publish_Me” & “Signaling_message_peer” – after which my client code does not work. There was no code there but I wrote some. Please see attached file for the code.

During testing I found some cases in ECSignalingChannel.m where the following method is there without any code to handle the above 2 events

- (void)socketIO:(SocketIO )socket didReceiveEvent:(SocketIOPacket )packet

This is a very critical and urgent requirement. 
The logs are not showing any error but attaching the error seen in the browser.
I would sincerely appreciate it if you can connect with me a we can go over this together and I can show you the code.

**Comment by zevarito** [comment]
@NarendraDigi I would like to see logs for `Publish_Me` and `Signaling_message_peer` you have mentioned.

Is P2P working for you Web/Web ?

**Comment by NarendraDigi** [comment]
Yes , its working on Web to Web .

**Comment by NarendraDigi** [comment]
Hi , 
I am attaching some screen shot of Web Socket debug logs . 
When I try to get video conferencing between Web to iOS App.

![p2p_conference1](https://cloud.githubusercontent.com/assets/25607523/22794666/f941d094-ef19-11e6-8a55-28edc5bdd83c.png)
![p2p_conference2](https://cloud.githubusercontent.com/assets/25607523/22794662/f9414692-ef19-11e6-9bf6-02af8d0770b3.png)
![p2p_conference3](https://cloud.githubusercontent.com/assets/25607523/22794664/f9415fba-ef19-11e6-916d-c313fd7cc2f6.png)
![p2p_conference4](https://cloud.githubusercontent.com/assets/25607523/22794663/f9416546-ef19-11e6-8d2c-3be7da6fd743.png)
![p2p_conference5](https://cloud.githubusercontent.com/assets/25607523/22794667/f942058c-ef19-11e6-9298-4854f905fbee.png)
![p2p_conference6](https://cloud.githubusercontent.com/assets/25607523/22794665/f941b690-ef19-11e6-8eca-fa10dcae7faf.png)
![p2p_conference7](https://cloud.githubusercontent.com/assets/25607523/22794668/f9666fa8-ef19-11e6-8e0a-3c6a1345f37f.png)

**Comment by NarendraDigi** [comment]
Hi  Zevarito,

I have implemented the library shared by you. it works perfectly fine for MCU mode.
however,  For P2P it display infinite loading screen thus i am unable to proceed.
If possible can you please share any specific code for P2P.

Thanks
Narendra Satpute

**Comment by notedit** [comment]
@NarendraDigi 
this repo does not handle  signaling_message_peer event,   it does not work in p2p mode.

**Comment by zevarito** [comment]
Added to master branch. Thanks @NarendraDigi.
