### ISSUE TITLE
Video track issue

### ISSUE THREAD

**Issue by ashar02** [zevarito/Licode-ErizoClientIOS#52]
I started to use video track enable/disable feature. It works great. But if I disable video track and a new subscriber comes in room. Then new subscriber can not listen the voice whose video was disabled but voice comes in very well. Any suggestion to fix this issue?

This happens if one side is iOS and other side is Web.

**Comment by zevarito** [comment]
Is the new subscriber trying to subscribe as video:true audio:true or just audio?

Can you share a code snippet?

**Comment by ashar02** [comment]
Let me share snippet with you shortly with scenario.

**Comment by ashar02** [comment]
I put a button on UI to on / off the video. It is basically option to mute or mute video in publishing.
I used [localStream.mediaStream removeVideoTrack:videoTrack] to mute and [localStream.mediaStream addVideoTrack:videoTrack] to unmute.

Javascript library gives option ecstream -> video track -> enable / disable option. It does not stop the stream at all but it reduces the video bandwidth utilization near to 0.

I think we override the video capture session and make the frame black and reduce the fps to achieve the same as javascript does. What you say?

**Comment by zevarito** [comment]
Well, it might work but is kinda tricky cause suppose you want to disable video due privacy concern, the video is actually sent anyway. I think is the app that should handle that scenario obfuscating the audio/video and being clear about that, but for the library I think is better to do it right or not to do it. 

@ashar02 did you try m58[0] build to see if that address your issue, cause there are a few bugs fixes there that could be related.

[0] https://github.com/zevarito/PodRTC/releases/tag/58.16.0.0

**Comment by zevarito** [comment]
Another solution, still form app side could be just drop the connection and create a new one with the media you want to share.

**Comment by ashar02** [comment]
True, but in this case on video mute / unmute, my video position on the remote end may change in this case.
