### ISSUE TITLE
Does it support SFU?

### ISSUE THREAD

**Issue by thehappycoder** [zevarito/Licode-ErizoClientIOS#53]
https://github.com/zevarito/Licode-ErizoClientIOS#features says that this library supports MCU & P2P modes but SFU is not mentioned.

**Comment by zevarito** [comment]
That line try to say it works either in P2P mode (client-2-client) or (client-server-client). MCU was the term adopted in early days of Licode to name that server component. Currently I think they refer as both MCU and SFU.
Probably the README should be updated to something less confusing.

Some interesting links:

https://github.com/lynckia/licode/issues/518
http://discourse.lynckia.com/t/licode-is-an-sfu-mcu/422
https://webrtcglossary.com/sfu/
https://webrtcglossary.com/mcu/
