### ISSUE TITLE
[INFO]

### ISSUE THREAD

**Issue by kekkokk** [zevarito/Licode-ErizoClientIOS#56]
Hi zevarito,
I'd like to know how you managed the switch from a network to another.
ex. from wifi to 3g. 
how do you manage sockets?

**Comment by zevarito** [comment]
I am afraid you need manage to reconnect and re-subscribe/publish streams.
I am working on a set of API changes and adding more functionality, perhaps does make sense to handle that scenario with some sort of policy for the room like `reconnect_on_network_change` within the lib itself.
