### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by Manal1Awad** [zevarito/Licode-ErizoClientIOS#60]
The sample introduce errors while building.
![screen shot 2017-06-18 at 11 10 14 am](https://user-images.githubusercontent.com/29517652/27259589-9d02009e-5416-11e7-98fc-d0bfab7bc781.png)

**Comment by zevarito** [comment]
Did you follow this steps? https://github.com/zevarito/Licode-ErizoClientIOS/wiki/Build-locally-and-link-from-your-project#troubleshoot

**Comment by Manal1Awad** [comment]
yes, i did

**Comment by Manal1Awad** [comment]
I follow the steps in the link, but i found many other errors ,
[image: Inline image 1]
