### ISSUE TITLE
Parse error for the official swift socketIO client

### ISSUE THREAD

**Issue by jasonchuang** [zevarito/Licode-ErizoClientIOS#62]
The ErizoClient build process shows errors on building project, but works for the original objc socketIO lib, any build steps for this latest official swift socketIO client replacement? Thanks
![parseissue](https://user-images.githubusercontent.com/4858414/28914120-20ca7b8e-786d-11e7-9292-367f17d8da73.png)

**Comment by juicechu** [comment]
the same question

**Comment by zevarito** [comment]
@jasonchuang @juicechu Ensure you have `Compile active architecture?` only to YES for Debug in the case you want to go with an specific commit before that `5.4.1` for that release vendored SocketIO has been replaced with a Pod.

**Comment by juicechu** [comment]
i found the reason you must complie in xcode 9.0
