### ISSUE TITLE
[Question] What would this error(argsData) be when it publish fails?

### ISSUE THREAD

**Issue by allenlinli** [zevarito/Licode-ErizoClientIOS#72]
Hi zevarito,

May I ask in the consistent  of `(!object || object == [NSNull null])`, what would `[argsData objectAtIndex:1]` be?

https://github.com/zevarito/Licode-ErizoClientIOS/blob/d851f56f51aeef2597763613a267b174460f5835/ErizoClient/rtc/ECSignalingChannel.m#L385

Thanks

**Comment by zevarito** [comment]
At the moment that piece of code was written Licode sent a string with the error description in that place.
