### ISSUE TITLE
Should we close peerConnection twice in RTCIceConnectionStateClosed and RTCIceConnectionStateDisconnected

### ISSUE THREAD

**Issue by allenlinli** [zevarito/Licode-ErizoClientIOS#73]
I was tracing a bug made by my own, and I found this part that I have a question.

Should we close peerConnection twice in `RTCIceConnectionStateClosed` and `RTCIceConnectionStateDisconnected`?

Or should we have a `didDisconnect` function to call? Or just igore `RTCIceConnectionStateDisconnected`? 

https://github.com/zevarito/Licode-ErizoClientIOS/blob/04b11d51cbd68fb0c15f0e636884cba9c542fdb7/ErizoClient/rtc/ECClient.m#L265

**Comment by zevarito** [comment]
@allenlinli those are really good concerns, definitely that need to be re-visited, please take a look at the link @kekkokk shared and especially this one[0] that is mentioned there, there is comprehensive explanation about how the standard should work, however in my experience it might differ a little between clients and platforms and ultimately you might have to step aside a little to make it work. Not telling this is the case but this[1] is an example of it.

[0] http://w3c.github.io/webrtc-pc/#rtciceconnectionstate-enum
[1] https://github.com/zevarito/Licode-ErizoClientIOS/commit/ffdf21b583703efead8f6bc889f1d7efbf88fade

**Comment by allenlinli** [comment]
Just found more reference here:
"disconnected":
`Checks to ensure that components are still connected failed for at least one component of the RTCPeerConnection. This is a less stringent test than "failed" and may trigger intermittently and resolve just as spontaneously on less reliable networks, or during temporary disconnections. When the problem resolves, the connection may return to the "connected" state.`

"closed":
The ICE agent for this RTCPeerConnection has shut down and is no longer handling requests.

Though I not still not sure should we have two `disconnect` here, still.

**Comment by allenlinli** [comment]
Since I opened this PR (https://github.com/zevarito/Licode-ErizoClientIOS/pull/75), this issue can be closed.
