### ISSUE TITLE
Do we need to handle error in `onUnPublishCallback:`, `onSubscribeMCUCallback`, `onUnSubscribeCallback:` within `ECSignalingChannel.m`?

### ISSUE THREAD

**Issue by allenlinli** [zevarito/Licode-ErizoClientIOS#76]
Hi @zevarito, 

I see we have error handling for `publish` (https://goo.gl/4MqriN), but not for unpblish(https://goo.gl/H7BEQo), subscribe(https://goo.gl/FEAbB8), unsubscribe(https://goo.gl/9Eso5K). Should we do the error handling for all of them?

That is, for example, replace `L_ERROR(@"signalingChannel Couldn't unpublish stream id: %@", streamId);` with `[self.roomDelegate signalingChannel:self didError:errorString];`?

I am not sure you did error handling here for `publish` only is because we'll receive error message from socket from here `socketIO on:@"error" callback:`(https://goo.gl/qE8X5F).

And here is reference from Lynckia (https://goo.gl/kPpPHP).

**Comment by zevarito** [comment]
> I see we have error handling for publish (https://goo.gl/4MqriN), but not for unpblish(https://goo.gl/H7BEQo), subscribe(https://goo.gl/FEAbB8), unsubscribe(https://goo.gl/9Eso5K). Should we do the error handling for all of them?
> 
> That is, for example, replace L_ERROR(@"signalingChannel Couldn't unpublish stream id: %@", streamId); with [self.roomDelegate signalingChannel:self didError:errorString];?

Yes, I think `roomDelegate:signalingChannel:didError` should become something like `roomDelegate:signalingChannel:errorStr:didError` allowing `errorStr` to be nil occasionally and `didError` enumerate signaling errors such as... `SignalingErrorPublish`, `SignalingErrorUnpublish`, `SignalingErrorSubscribing` etc. Not having those right now doesn't mean that you will not realize when the subscription fails (webrtc layer), but it is true that you will not notice if ErizoController is failing or is down right after getting the token and connecting to the room where you should be able to notice.

**Comment by zevarito** [comment]
@allenlinli I'll close this since it is not an issue more like a feature missing, if you want to work on this just open a PR and we can have the discussion there, thanks!
